//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudgetPrep : DbContext
    {
        public BudgetPrep()
            : base("name=BudgetPrep")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountCode> AccountCodes { get; set; }
        public virtual DbSet<BPEventLog> BPEventLogs { get; set; }
        public virtual DbSet<BPLanguage> BPLanguages { get; set; }
        public virtual DbSet<BudgetMenguru> BudgetMengurus { get; set; }
        public virtual DbSet<BudgetPerjawatan> BudgetPerjawatans { get; set; }
        public virtual DbSet<BudgetProjek> BudgetProjeks { get; set; }
        public virtual DbSet<FieldMenguru> FieldMengurus { get; set; }
        public virtual DbSet<FieldPerjawatan> FieldPerjawatans { get; set; }
        public virtual DbSet<GroupPerjawatan> GroupPerjawatans { get; set; }
        public virtual DbSet<JuncBgtMengurusSegDtl> JuncBgtMengurusSegDtls { get; set; }
        public virtual DbSet<JuncBgtPerjawatanSegDtl> JuncBgtPerjawatanSegDtls { get; set; }
        public virtual DbSet<JuncBgtProjekSegDtl> JuncBgtProjekSegDtls { get; set; }
        public virtual DbSet<JuncRolePage> JuncRolePages { get; set; }
        public virtual DbSet<JuncUserRole> JuncUserRoles { get; set; }
        public virtual DbSet<MasterGroup> MasterGroups { get; set; }
        public virtual DbSet<MasterMenu> MasterMenus { get; set; }
        public virtual DbSet<MasterPage> MasterPages { get; set; }
        public virtual DbSet<MasterRole> MasterRoles { get; set; }
        public virtual DbSet<MasterUser> MasterUsers { get; set; }
        public virtual DbSet<PeriodMenguru> PeriodMengurus { get; set; }
        public virtual DbSet<PeriodPerjawatan> PeriodPerjawatans { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<SegmentDetail> SegmentDetails { get; set; }
        public virtual DbSet<UserMengurusWorkflow> UserMengurusWorkflows { get; set; }
        public virtual DbSet<UserPerjawatanWorkflow> UserPerjawatanWorkflows { get; set; }
        public virtual DbSet<UserSegDtlWorkflow> UserSegDtlWorkflows { get; set; }
        public virtual DbSet<YearEnd> YearEnds { get; set; }
        public virtual DbSet<YearUploadSetup> YearUploadSetups { get; set; }
        public virtual DbSet<PerbelanjaanSebenar> PerbelanjaanSebenars { get; set; }
        public virtual DbSet<PeruntukanAsal> PeruntukanAsals { get; set; }
        public virtual DbSet<PeruntukanDipinda> PeruntukanDipindas { get; set; }
    }
}
