//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPEntities : DbContext
    {
        public BPEntities()
            : base("name=BPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< HEAD
        public DbSet<BPEventLog> BPEventLogs { get; set; }
        public DbSet<MasterUser> MasterUsers { get; set; }
        public DbSet<MasterRole> MasterRoles { get; set; }
=======
        public DbSet<USER> USERS { get; set; }
>>>>>>> 51c6cb0a8522e20edf9ecab4038564a4b0e3c4ea
    }
}
