//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldMenguru
    {
        public FieldMenguru()
        {
            this.PeriodMengurus = new HashSet<PeriodMenguru>();
        }
    
        public int FieldMengurusID { get; set; }
        public string FieldMengurusSDesc { get; set; }
        public string FieldMengurusDesc { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTimeStamp { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTimeStamp { get; set; }
    
        public virtual ICollection<PeriodMenguru> PeriodMengurus { get; set; }
    }
}
