//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuncUserRole
    {
<<<<<<< HEAD
        public int JuncUserRoleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Status { get; set; }
    
        public virtual MasterRole MasterRole { get; set; }
        public virtual MasterUser MasterUser { get; set; }
=======
        public int UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Status { get; set; }
    
        public virtual MasterUser MasterUser { get; set; }
        public virtual MasterRole MasterRole { get; set; }
>>>>>>> fa2a2893ae1d7e783d8591f454ef428f3a40756b
    }
}
