//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterPage()
        {
            this.JuncRolePages = new HashSet<JuncRolePage>();
        }
    
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string PagePath { get; set; }
        public int PageOrder { get; set; }
        public Nullable<int> ParentPageID { get; set; }
        public Nullable<int> MenuID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JuncRolePage> JuncRolePages { get; set; }
        public virtual MasterMenu MasterMenu { get; set; }
    }
}
