//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRole
    {
        public MasterRole()
        {
<<<<<<< HEAD
            this.JuncRolePages = new HashSet<JuncRolePage>();
=======
>>>>>>> fa2a2893ae1d7e783d8591f454ef428f3a40756b
            this.JuncUserRoles = new HashSet<JuncUserRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> RUID { get; set; }
        public string RoleStatus { get; set; }
    
<<<<<<< HEAD
        public virtual ICollection<JuncRolePage> JuncRolePages { get; set; }
=======
>>>>>>> fa2a2893ae1d7e783d8591f454ef428f3a40756b
        public virtual ICollection<JuncUserRole> JuncUserRoles { get; set; }
    }
}
