//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterMenu
    {
        public MasterMenu()
        {
            this.MasterPages = new HashSet<MasterPage>();
        }
    
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public int MenuOrder { get; set; }
        public string MenuIcon { get; set; }
    
        public virtual ICollection<MasterPage> MasterPages { get; set; }
    }
}
