//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeruntukanDipinda
    {
        public string BudgetAccount { get; set; }
        public string Description { get; set; }
        public string BudgetType { get; set; }
        public Nullable<int> BudgetAccKey { get; set; }
        public Nullable<int> BudgetLedgerKey { get; set; }
        public Nullable<int> BudgetYear { get; set; }
        public string Type { get; set; }
        public decimal BudgetAmount { get; set; }
    }
}
