//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SegmentDetail()
        {
            this.JuncBgtMengurusSegDtls = new HashSet<JuncBgtMengurusSegDtl>();
            this.JuncBgtPerjawatanSegDtls = new HashSet<JuncBgtPerjawatanSegDtl>();
            this.JuncBgtProjekSegDtls = new HashSet<JuncBgtProjekSegDtl>();
            this.UserSegDtlWorkflows = new HashSet<UserSegDtlWorkflow>();
        }
    
        public int SegmentDetailID { get; set; }
        public Nullable<int> SegmentID { get; set; }
        public string DetailCode { get; set; }
        public string DetailDesc { get; set; }
        public Nullable<int> ParentDetailID { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTimeStamp { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JuncBgtMengurusSegDtl> JuncBgtMengurusSegDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JuncBgtPerjawatanSegDtl> JuncBgtPerjawatanSegDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JuncBgtProjekSegDtl> JuncBgtProjekSegDtls { get; set; }
        public virtual Segment Segment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSegDtlWorkflow> UserSegDtlWorkflows { get; set; }
    }
}
