//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSegDtlWorkflow
    {
        public int UserSegDtlWorkflowID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SegmentDetailID { get; set; }
        public string Status { get; set; }
    
        public virtual SegmentDetail SegmentDetail { get; set; }
        public virtual MasterUser MasterUser { get; set; }
    }
}
